# Generated by Django 5.0.1 on 2024-02-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attributename_zobrazit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributename',
            old_name='kod',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='hodnota_atributu',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='nazev_atributu',
        ),
        migrations.RemoveField(
            model_name='attributename',
            name='nazev',
        ),
        migrations.RemoveField(
            model_name='attributename',
            name='zobrazit',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='hodnota',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='attributes_ids',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='nazev',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='obrazek_id',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='products_ids',
        ),
        migrations.RemoveField(
            model_name='image',
            name='obrazek',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mena',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nazev',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='nazev',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='obrazek_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributename'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributevalue'),
        ),
        migrations.AddField(
            model_name='attributename',
            name='display',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='attributename',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='attributes',
            field=models.ManyToManyField(to='api.attribute'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='products',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
