# Generated by Django 5.0.1 on 2024-02-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_attribute_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='products',
            field=models.ManyToManyField(blank=True, to='api.product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(blank=True, default='CZK', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
